### ISSUE TITLE
Build with latest S4TF toolchain fails with unresolved `_Raw` identifier

### ISSUE THREAD

**Issue by vojtamolda** [eaplatanios/swift-rl#3]
Hello @eaplatanios,

You've got a really nice repository here! I wanted to play around with it but I'm getting errors that the `_Raw` symbol is undefined.

It used to work fine two commits ago (d2a95d0a0f98c7f42fb2c95e73d572341691379e) but the `master` branch right now doesn't compile because of this error:

```bash
$ swift build
...
swift-rl/Sources/ReinforcementLearning/Utilities/Protocols.swift:82:12: error: use
    of unresolved identifier '_Raw'
    self = _Raw.tensorScatterUpdate(self, indices: indices, updates: values)
           ^~~~
...
```

 What's the version of S4TF toolchain you use? I work with the binary releases from [s4tf repo](https://github.com/tensorflow/swift/blob/master/Installation.md) for XCode 11 on macOS. The `0.5.0` release from  9/17 and also the latest nightly build `4d1c1df58f` from 10/7 both fail with the same error.

The fix is very straightforward (i.e. revert back to `Raw`) but I wanted to check with you because I'm obviously missing something and the whole S4TF project is still very actively developed.

Cheers,

  Vojta

**Comment by eaplatanios** [comment]
@vojtamolda sorry for the late response. Using a more up-to-date swift toolchain will also resolve your issue. :)

**Comment by vojtamolda** [comment]
No worries. Thanks!
