### ISSUE TITLE
Rendering.swift

### ISSUE THREAD

**Issue by 8bitmp3** [eaplatanios/swift-rl#4]
Hey @eaplatanios Nice work, thanks for the efforts. Noticed that the link to ["Visualization using OpenGL for all of the currently implemented environments"](https://github.com/eaplatanios/swift-rl/blob/master/Sources/ReinforcementLearning/Environments/Rendering.swift) in README does not work - `Rendering.swift`is not in `../Environments/Rendering/`.

**Comment by eaplatanios** [comment]
@8bitmp3 sorry about this. I updated the README to point to the right file.

**Comment by 8bitmp3** [comment]
No worries 👍 Welcome back @eaplatanios
