### ISSUE TITLE
glfw3's gettext dependency installation

### ISSUE THREAD

**Issue by 8bitmp3** [eaplatanios/swift-rl#5]
`brew install --HEAD git glfw3` won't complete as the `gettext-0.20.1` dependency fails to download and install including from source. Haven't been able to manually build gettext v0.20.1 either. If you have any suggestions LMK.

This may be related https://discourse.brew.sh/t/mac-os-10-15-catalina-issues/5001/24

**Comment by eaplatanios** [comment]
@8bitmp3 sorry I was offline because I'm graduating soon and needed to focus on my dissertation. Just got back to check this. Is this still an issue for you?

**Comment by 8bitmp3** [comment]
@eaplatanios resolved today, installation works now 🕶 hope the thesis defense went well. feel free to share your arxiv link if you can. we love your `swift-rl` work

**Comment by eaplatanios** [comment]
Thanks @8bitmp3 ! My defense is actually in about a month from now but I'm submitting my dissertation draft this week. I'll let you know once I post it online. I'm glad you like `swift-rl` :) I hope I can continue working on it soon.
